# Generated by Django 3.1.2 on 2020-10-09 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="abstract",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="article",
            name="content",
            field=models.TextField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="article",
            name="created",
            field=models.DateField(auto_created=True, null=True),
        ),
        migrations.AlterField(
            model_name="article",
            name="title",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="article",
            name="updated",
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.CreateModel(
            name="BookRecomendation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "article",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="blog.article",
                    ),
                ),
            ],
        ),
    ]
