# Generated by Django 3.1.2 on 2020-10-10 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20201010_0511'),
    ]

    operations = [
        migrations.RenameField(
            model_name='frace',
            old_name='frase',
            new_name='frace',
        ),
    ]
