# Generated by Django 3.1.2 on 2020-10-10 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0011_contactcard_updated"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactcard",
            name="experience",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="blog.jobexperience",
            ),
        ),
    ]
