# Generated by Django 3.1.2 on 2021-04-07 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0017_auto_20210302_0426"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactcard",
            name="skype",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="contactcard",
            name="twitter",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
