# Generated by Django 3.1.2 on 2022-03-18 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_message_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
